<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8TAIC7t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8TAIC7t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8TAIC7t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8TAIC7t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8TAIC7t\App_KernelDevDebugContainer([
    'container.build_hash' => '8TAIC7t',
    'container.build_id' => 'cd42fe69',
    'container.build_time' => 1692383424,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8TAIC7t');
